PROBLEM 1

The result is [[6, 29, -20], [12, 52, 38], [-18, -51, -48]].
Each new cell of the product matrix will be calculated follow the rule that: $c[i][j] = a[i][1]*b[1][j] + ... + a[i][n]*b[n][j]$.
It is the sum of $a[i][k]*b[k][j]$ (where $k$ is from 1 to n)

In [1]:
import numpy as np

#problem 2
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(np.matmul(a_ndarray, b_ndarray))
print(np.dot(a_ndarray, b_ndarray))
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [2]:
#problem 3
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
b_ndarray_transpose = b_ndarray.T
result = []
for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray)):
        result.append(sum(a_ndarray[i] * b_ndarray_transpose[j]))

result = np.array(result)
result = result.reshape((len(a_ndarray), len(b_ndarray)))

print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
#problem 4

def calculate_matrix_multiplication(a_array, b_array):
    a_array = np.array(a_array)
    b_array = np.array(b_array).T
    result = []
    for i in range(len(a_array)):
        for j in range(len(b_array)):
            result.append(sum(a_array[i] * b_array[j]))
    result = np.array(result)
    result = result.reshape((len(a_array), len(b_array)))
    return result

print(calculate_matrix_multiplication([[-1, 2, 3], [4, -5, 6], [7, 8, -9]], [[0, 2, 1], [0, 2, -8], [2, 9, -1]]))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
#problem 5

def calculate_matrix_multiplication(a_array, b_array):
    if (len(a_array[0]) != len(b_array)):
        print("Invalid input! Number of columns of matrix A is not equal to number of rows of matrix B")
        return     
    a_array = np.array(a_array)
    b_array = np.array(b_array).T
    result = []
    for i in range(len(a_array)):
        for j in range(len(b_array)):
            result.append(sum(a_array[i] * b_array[j]))
    result = np.array(result)
    result = result.reshape((len(a_array), len(b_array)))
    return result

print(calculate_matrix_multiplication([[-1, 2], [4, -5]], [[0, 2, 1], [0, 2, -8], [2, 9, -1]]))

Invalid input! Number of columns of matrix A is not equal to number of rows of matrix B
None


In [5]:
#problem 6

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
b_ndarray_transpose = np.transpose(b_ndarray)
result = []
for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray)):
        result.append(sum(a_ndarray[i] * b_ndarray_transpose[j]))

result = np.array(result)
result = result.reshape((len(a_ndarray), len(b_ndarray)))

print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
