In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Variance :", scaler.var_)
X_std = scaler.transform(X)
print("X standard: ", X_std)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]
X standard:  [[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# PROBLEM 1: Enumeration of classes used so far

I find out some classes that i use for the previous assignments that are "LinearRegression", "ListedColormap", "DecisionTreeClassifier", "RandomForestClassifier", "KNeighborsClassifier", "LogisticRegression".

From pandas we have some classes like "DataFrame", "Series", "GroupBy", "Plotting". From matplotlib, we get "Figure", "Axes".

# PROBLEM 2: Enumeration of methods and instance variables used so far

- Some methods that I used for the previous assignment: "train_test_split", "fit_transform", "predict", "mean_squared_error", "fit".
- Some attribute I made use of from the previous assignment: "shape", "target", "data", "columns", "index"

# PROBLEM 3: Creating a standardized class by scratch

In [2]:
class ScratchStandardScaler():
    """
    Attributes
    ----------
    mean_ : ndarray, shape(n_features,)
    var_ : ndarray, shape(n_features,)
    """
    def fit(self, X):
        """
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        pass
    def transform(self, X):
        """
        fit
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
        Returns
        ----------
        X_scaled : ndarray, shape (n_samples, n_features)
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [3]:
scaler1 = ScratchStandardScaler()
scaler1.fit(X)
print("Mean :", scaler1.mean_)
print("Variance :", scaler1.var_)
X_std_1 = scaler1.transform(X)
print("X standard: ", X_std_1)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]
X standard:  [[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# PROBLEM 4: Creating a class that performs 4 arithmetic operations

In [4]:
class Calculator():
    def __init__(self, value):
        if not isinstance(value, (int, float, complex)):
            print('Cannot process value that is not numeric type!')
            return
        self.value = value
            
    def add(self, value1):
        if not isinstance(value1, (int, float, complex)):
            print('Cannot process value that is not numeric type!')
            return
        self.value += value1
            
    def substract(self, value1):
        if not isinstance(value1, (int, float, complex)):
            print('Cannot process value that is not numeric type!')
            return
        self.value -= value1
            
    def multiply(self, value1):
        if not isinstance(value1, (int, float, complex)):
            print('Cannot process value that is not numeric type!')
            return
        self.value *= value1
    def divide(self, value1):
        if not isinstance(value1, (int, float, complex)):
            print('Cannot process value that is not numeric type!')
            return
        if value1 == 0:
            print("Division by zero!")
            return
        self.value /= value1

In [5]:
myCalculator = Calculator(10)
myCalculator.add('5')
myCalculator.add(5)
print('Value:', myCalculator.value)
myCalculator.substract(5)
print('Value:', myCalculator.value)
myCalculator.multiply(5)
print('Value:', myCalculator.value)
myCalculator.divide(0)
print('Value:', myCalculator.value)
myCalculator.divide(3)
print('Value:', myCalculator.value)

Cannot process value that is not numeric type!
Value: 15
Value: 10
Value: 50
Division by zero!
Value: 50
Value: 16.666666666666668
